### ISSUE TITLE
issues using kmssigner with x509.CreateCertificate()

### ISSUE THREAD

**Issue by joemiller** [heptiolabs/google-kms-pgp#2]
I have been experimenting with using the kmssigner's `crypto.Signer` interface to sign X509 certs with `x509.CreateCertificate()` and running into an issue with the `Public()` implementation.

The current code returns a value:
```
 func (k *kmsSigner) Public() crypto.PublicKey {
   return k.pubkey
}
```

When used with `x509.CreateCertificate()` this results in the error:

```
2018/09/07 15:02:26 Failed to create certificate: x509: only RSA and ECDSA public keys supported
```

Tracing this back through the x509 package:
```
func CreateCertificate(rand io.Reader, template, parent *Certificate, pub, priv interface{}) (cert []byte, err error) {
...
	hashFunc, signatureAlgorithm, err := signingParamsForPublicKey(key.Public(), template.SignatureAlgorithm)
...

func signingParamsForPublicKey(pub interface{}, requestedSigAlgo SignatureAlgorithm) (hashFunc crypto.Hash, sigAlgo pkix.AlgorithmIdentifier, err error) {
	var pubType PublicKeyAlgorithm

	switch pub := pub.(type) {
	case *rsa.PublicKey:
...
default:
		err = errors.New("x509: only RSA and ECDSA keys supported")
```

The issue here is that the x509 package is expecting `Public()` to return a pointer.

A slight modification to return a pointer allows for `x509.CreateCertificate()` to complete without error:
```
 func (k *kmsSigner) Public() crypto.PublicKey {
   return &k.pubkey
}
```

However this leads to the openpgp lib panic'ing because it is expecting a value instead of a pointer:
```
panic: openpgp: unknown crypto.Signer type in NewSignerPrivateKey
```

```
func NewSignerPrivateKey(currentTime time.Time, signer crypto.Signer) *PrivateKey {
   pk := new(PrivateKey)
   switch pubkey := signer.Public().(type) {
   case rsa.PublicKey:
     pk.PublicKey = *NewRSAPublicKey(currentTime, &pubkey)
     pk.PubKeyAlgo = PubKeyAlgoRSASignOnly
 ...
  default:
     panic("openpgp: unknown crypto.Signer type in NewSignerPrivateKey")
  }
```

At this point I'm not quite sure how to resolve this within `kmssigner` such that it could be used with both the x509 and openpgp packages, but I thought I'd leave this note here in case some more experienced gophers have some ideas. thanks.

**Comment by mattmoyer** [comment]
Thanks for finding this. I also noticed that it was kind of weird that the openpgp package has a hardcoded check for the non-pointer version of `rsa.PublicKey` vs. the pointer. I was surprised that both the pointer and non-pointer versions worked, but `crypto.PublicKey` is just [defined as](https://github.com/golang/go/blob/0f72e79856d246af85c449f9e5a357ba751cd234/src/crypto/crypto.go#L107-L108):

```go
type PublicKey interface{}
```

It seems we probably need to fix this in https://github.com/golang/crypto/.

Until then, perhaps we could make serparate `kmssigner.NewForOpenPGP()` vs. `kmssigner.NewForX509()` methods that return slightly different implementations of `crypto.Signer()`?

**Comment by mattmoyer** [comment]
Filed upstream https://github.com/golang/go/issues/27606.

**Comment by joemiller** [comment]
@mattmoyer Thanks for the sanity check, I also suspected an upstream/stdlib issue.

+1 to the NewForOpenPGP/NewForX509 temp workaround!

also thanks again for writing the package, it's exactly what I was looking for at the right time =)

**Comment by mozillazg** [comment]
The rated issue has been fixed in upstream: https://github.com/golang/crypto/commit/e3636079e1a4c1f337f212cc5cd2aca108f6c900 .
